name: glgshop site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the glgshop/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/glgshop -v ${{ github.workspace }}/_site:/srv/glgshop/_site \
        glgshop/builder:latest /bin/bash -c "chmod -R 777 /srv/glgshop && glgshop build --future"
